name: Language Stats

on:
  workflow_dispatch:

jobs:
  language-stats:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install cloc
      run: choco install cloc -y

    - name: Run cloc and generate stats
      run: |
        cloc --json --exclude-dir=.github | Out-File -FilePath stats.json

    - name: Parse stats and generate percentages
      run: |
        echo "::set-output name=languages::$(Get-Content stats.json | ConvertFrom-Json | Select-Object -ExpandProperty SUM.language)" > stats.json
        echo "::set-output name=percentages::$(Get-Content stats.json | ConvertFrom-Json | Select-Object -ExpandProperty SUM.code | ForEach-Object { $_.GetEnumerator() | ForEach-Object { [PSCustomObject]@{ Key = $_.Key; Value = [Math]::Round($_.Value / $_.Parent.code * 100, 2) } } })" > stats.json

    - name: Display language percentages
      run: |
        echo "Language percentages:"
        Get-Content stats.json | ConvertFrom-Json | Select-Object -ExpandProperty percentages
